//go:build !ignore_autogenerated

/*
Copyright 2024 Universidad Carlos III de Madrid

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/Networks-it-uc3m/L2S-M/api/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverlayCluster) DeepCopyInto(out *OverlayCluster) {
	*out = *in
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(apiv1.NodeConfigSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverlayCluster.
func (in *OverlayCluster) DeepCopy() *OverlayCluster {
	if in == nil {
		return nil
	}
	out := new(OverlayCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverlayLink) DeepCopyInto(out *OverlayLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverlayLink.
func (in *OverlayLink) DeepCopy() *OverlayLink {
	if in == nil {
		return nil
	}
	out := new(OverlayLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverlayTopology) DeepCopyInto(out *OverlayTopology) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]OverlayCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]OverlayLink, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverlayTopology.
func (in *OverlayTopology) DeepCopy() *OverlayTopology {
	if in == nil {
		return nil
	}
	out := new(OverlayTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceClusterConfig) DeepCopyInto(out *SliceClusterConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceClusterConfig.
func (in *SliceClusterConfig) DeepCopy() *SliceClusterConfig {
	if in == nil {
		return nil
	}
	out := new(SliceClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceClusterStatus) DeepCopyInto(out *SliceClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceClusterStatus.
func (in *SliceClusterStatus) DeepCopy() *SliceClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SliceClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceNetwork) DeepCopyInto(out *SliceNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceNetwork.
func (in *SliceNetwork) DeepCopy() *SliceNetwork {
	if in == nil {
		return nil
	}
	out := new(SliceNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SliceNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceNetworkList) DeepCopyInto(out *SliceNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SliceNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceNetworkList.
func (in *SliceNetworkList) DeepCopy() *SliceNetworkList {
	if in == nil {
		return nil
	}
	out := new(SliceNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SliceNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceNetworkSpec) DeepCopyInto(out *SliceNetworkSpec) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(apiv1.ProviderSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceNetworkSpec.
func (in *SliceNetworkSpec) DeepCopy() *SliceNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(SliceNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceNetworkStatus) DeepCopyInto(out *SliceNetworkStatus) {
	*out = *in
	if in.ClusterStatuses != nil {
		in, out := &in.ClusterStatuses, &out.ClusterStatuses
		*out = make([]SliceClusterStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceNetworkStatus.
func (in *SliceNetworkStatus) DeepCopy() *SliceNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(SliceNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceOverlay) DeepCopyInto(out *SliceOverlay) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceOverlay.
func (in *SliceOverlay) DeepCopy() *SliceOverlay {
	if in == nil {
		return nil
	}
	out := new(SliceOverlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SliceOverlay) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceOverlayList) DeepCopyInto(out *SliceOverlayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SliceOverlay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceOverlayList.
func (in *SliceOverlayList) DeepCopy() *SliceOverlayList {
	if in == nil {
		return nil
	}
	out := new(SliceOverlayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SliceOverlayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceOverlaySpec) DeepCopyInto(out *SliceOverlaySpec) {
	*out = *in
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(apiv1.ProviderSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SwitchTemplate != nil {
		in, out := &in.SwitchTemplate, &out.SwitchTemplate
		*out = new(apiv1.SwitchTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = new(OverlayTopology)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceOverlaySpec.
func (in *SliceOverlaySpec) DeepCopy() *SliceOverlaySpec {
	if in == nil {
		return nil
	}
	out := new(SliceOverlaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SliceOverlayStatus) DeepCopyInto(out *SliceOverlayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SliceOverlayStatus.
func (in *SliceOverlayStatus) DeepCopy() *SliceOverlayStatus {
	if in == nil {
		return nil
	}
	out := new(SliceOverlayStatus)
	in.DeepCopyInto(out)
	return out
}
