apiVersion: apps/v1
kind: Deployment
metadata:
  name: l2sm-md-server
  labels:
    app: l2sm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: l2sm
  template:
    metadata:
      labels:
        app: l2sm
    spec:
      containers:
      - name: l2sm-md-server-container
        image: alexdecb/l2sm-md:0.1  
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051  
        volumeMounts:
        - name: kubeconfigs
          mountPath: "/etc/l2sm/.kube/"  # Mount the ConfigMap at this path
          readOnly: true  # The ConfigMap should be read-only to prevent modification
      volumes:
      - name: kubeconfigs
        configMap:
          name: kubeconfigs  
        
