// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: l2sces.proto

package l2sces

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	DnsPort       string                 `protobuf:"bytes,3,opt,name=dns_port,json=dnsPort,proto3" json:"dns_port,omitempty"`
	SdnPort       string                 `protobuf:"bytes,4,opt,name=sdn_port,json=sdnPort,proto3" json:"sdn_port,omitempty"`
	OfPort        string                 `protobuf:"bytes,5,opt,name=of_port,json=ofPort,proto3" json:"of_port,omitempty"`
	DnsGrpcPort   string                 `protobuf:"bytes,6,opt,name=dns_grpc_port,json=dnsGrpcPort,proto3" json:"dns_grpc_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_l2sces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{0}
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Provider) GetDnsPort() string {
	if x != nil {
		return x.DnsPort
	}
	return ""
}

func (x *Provider) GetSdnPort() string {
	if x != nil {
		return x.SdnPort
	}
	return ""
}

func (x *Provider) GetOfPort() string {
	if x != nil {
		return x.OfPort
	}
	return ""
}

func (x *Provider) GetDnsGrpcPort() string {
	if x != nil {
		return x.DnsGrpcPort
	}
	return ""
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointA     string                 `protobuf:"bytes,1,opt,name=endpointA,proto3" json:"endpointA,omitempty"`
	EndpointB     string                 `protobuf:"bytes,2,opt,name=endpointB,proto3" json:"endpointB,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_l2sces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetEndpointA() string {
	if x != nil {
		return x.EndpointA
	}
	return ""
}

func (x *Link) GetEndpointB() string {
	if x != nil {
		return x.EndpointB
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_l2sces_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{2}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type RestConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BearerToken   string                 `protobuf:"bytes,1,opt,name=bearer_token,json=bearerToken,proto3" json:"bearer_token,omitempty"`
	ApiKey        string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestConfig) Reset() {
	*x = RestConfig{}
	mi := &file_l2sces_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestConfig) ProtoMessage() {}

func (x *RestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestConfig.ProtoReflect.Descriptor instead.
func (*RestConfig) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{3}
}

func (x *RestConfig) GetBearerToken() string {
	if x != nil {
		return x.BearerToken
	}
	return ""
}

func (x *RestConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type Cluster struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RestConfig     *RestConfig            `protobuf:"bytes,2,opt,name=rest_config,json=restConfig,proto3" json:"rest_config,omitempty"`
	Overlay        *Overlay               `protobuf:"bytes,3,opt,name=overlay,proto3" json:"overlay,omitempty"`
	GatewayNode    *Node                  `protobuf:"bytes,4,opt,name=gateway_node,json=gatewayNode,proto3" json:"gateway_node,omitempty"`
	Namespace      string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodAddressPool string                 `protobuf:"bytes,6,opt,name=pod_address_pool,json=podAddressPool,proto3" json:"pod_address_pool,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_l2sces_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{4}
}

func (x *Cluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cluster) GetRestConfig() *RestConfig {
	if x != nil {
		return x.RestConfig
	}
	return nil
}

func (x *Cluster) GetOverlay() *Overlay {
	if x != nil {
		return x.Overlay
	}
	return nil
}

func (x *Cluster) GetGatewayNode() *Node {
	if x != nil {
		return x.GatewayNode
	}
	return nil
}

func (x *Cluster) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Cluster) GetPodAddressPool() string {
	if x != nil {
		return x.PodAddressPool
	}
	return ""
}

type Overlay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Nodes         []string               `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links         []*Link                `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overlay) Reset() {
	*x = Overlay{}
	mi := &file_l2sces_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overlay) ProtoMessage() {}

func (x *Overlay) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overlay.ProtoReflect.Descriptor instead.
func (*Overlay) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{5}
}

func (x *Overlay) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *Overlay) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Overlay) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type L2Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provider      *Provider              `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	PodCidr       string                 `protobuf:"bytes,3,opt,name=pod_cidr,json=podCidr,proto3" json:"pod_cidr,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Clusters      []*Cluster             `protobuf:"bytes,5,rep,name=clusters,proto3" json:"clusters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2Network) Reset() {
	*x = L2Network{}
	mi := &file_l2sces_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Network) ProtoMessage() {}

func (x *L2Network) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Network.ProtoReflect.Descriptor instead.
func (*L2Network) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{6}
}

func (x *L2Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L2Network) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *L2Network) GetPodCidr() string {
	if x != nil {
		return x.PodCidr
	}
	return ""
}

func (x *L2Network) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *L2Network) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

type Slice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Clusters      []*Cluster             `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Links         []*Link                `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slice) Reset() {
	*x = Slice{}
	mi := &file_l2sces_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{7}
}

func (x *Slice) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *Slice) GetClusters() []*Cluster {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *Slice) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

// Requests and Responses for Network
type CreateNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *L2Network             `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkRequest) Reset() {
	*x = CreateNetworkRequest{}
	mi := &file_l2sces_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkRequest) ProtoMessage() {}

func (x *CreateNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateNetworkRequest) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{8}
}

func (x *CreateNetworkRequest) GetNetwork() *L2Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *CreateNetworkRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type FieldPatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A dot path or JSONPath-like string:
	// e.g. "spec.template.metadata.labels.l2sm"
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The desired value for that path
	// e.g. "true"
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldPatch) Reset() {
	*x = FieldPatch{}
	mi := &file_l2sces_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPatch) ProtoMessage() {}

func (x *FieldPatch) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPatch.ProtoReflect.Descriptor instead.
func (*FieldPatch) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{9}
}

func (x *FieldPatch) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FieldPatch) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Patches       []*FieldPatch          `protobuf:"bytes,2,rep,name=patches,proto3" json:"patches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNetworkResponse) Reset() {
	*x = CreateNetworkResponse{}
	mi := &file_l2sces_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNetworkResponse) ProtoMessage() {}

func (x *CreateNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNetworkResponse.ProtoReflect.Descriptor instead.
func (*CreateNetworkResponse) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{10}
}

func (x *CreateNetworkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateNetworkResponse) GetPatches() []*FieldPatch {
	if x != nil {
		return x.Patches
	}
	return nil
}

type DeleteNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       *L2Network             `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkRequest) Reset() {
	*x = DeleteNetworkRequest{}
	mi := &file_l2sces_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkRequest) ProtoMessage() {}

func (x *DeleteNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteNetworkRequest) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteNetworkRequest) GetNetwork() *L2Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *DeleteNetworkRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeleteNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNetworkResponse) Reset() {
	*x = DeleteNetworkResponse{}
	mi := &file_l2sces_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNetworkResponse) ProtoMessage() {}

func (x *DeleteNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNetworkResponse.ProtoReflect.Descriptor instead.
func (*DeleteNetworkResponse) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteNetworkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Requests and Responses for Slice
type CreateSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slice         *Slice                 `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSliceRequest) Reset() {
	*x = CreateSliceRequest{}
	mi := &file_l2sces_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSliceRequest) ProtoMessage() {}

func (x *CreateSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSliceRequest.ProtoReflect.Descriptor instead.
func (*CreateSliceRequest) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{13}
}

func (x *CreateSliceRequest) GetSlice() *Slice {
	if x != nil {
		return x.Slice
	}
	return nil
}

func (x *CreateSliceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CreateSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSliceResponse) Reset() {
	*x = CreateSliceResponse{}
	mi := &file_l2sces_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSliceResponse) ProtoMessage() {}

func (x *CreateSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSliceResponse.ProtoReflect.Descriptor instead.
func (*CreateSliceResponse) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{14}
}

func (x *CreateSliceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slice         *Slice                 `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSliceRequest) Reset() {
	*x = DeleteSliceRequest{}
	mi := &file_l2sces_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSliceRequest) ProtoMessage() {}

func (x *DeleteSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSliceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSliceRequest) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSliceRequest) GetSlice() *Slice {
	if x != nil {
		return x.Slice
	}
	return nil
}

func (x *DeleteSliceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeleteSliceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSliceResponse) Reset() {
	*x = DeleteSliceResponse{}
	mi := &file_l2sces_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSliceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSliceResponse) ProtoMessage() {}

func (x *DeleteSliceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSliceResponse.ProtoReflect.Descriptor instead.
func (*DeleteSliceResponse) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSliceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Requests and Responses for Overlays (existing)
type CreateOverlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overlay       *Overlay               `protobuf:"bytes,1,opt,name=overlay,proto3" json:"overlay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOverlayRequest) Reset() {
	*x = CreateOverlayRequest{}
	mi := &file_l2sces_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOverlayRequest) ProtoMessage() {}

func (x *CreateOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOverlayRequest.ProtoReflect.Descriptor instead.
func (*CreateOverlayRequest) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{17}
}

func (x *CreateOverlayRequest) GetOverlay() *Overlay {
	if x != nil {
		return x.Overlay
	}
	return nil
}

type CreateOverlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOverlayResponse) Reset() {
	*x = CreateOverlayResponse{}
	mi := &file_l2sces_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOverlayResponse) ProtoMessage() {}

func (x *CreateOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOverlayResponse.ProtoReflect.Descriptor instead.
func (*CreateOverlayResponse) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{18}
}

func (x *CreateOverlayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddClusterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderName   string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderDomain string                 `protobuf:"bytes,2,opt,name=provider_domain,json=providerDomain,proto3" json:"provider_domain,omitempty"`
	SliceName      string                 `protobuf:"bytes,3,opt,name=slice_name,json=sliceName,proto3" json:"slice_name,omitempty"`
	Cluster        *Cluster               `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddClusterRequest) Reset() {
	*x = AddClusterRequest{}
	mi := &file_l2sces_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClusterRequest) ProtoMessage() {}

func (x *AddClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClusterRequest.ProtoReflect.Descriptor instead.
func (*AddClusterRequest) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{19}
}

func (x *AddClusterRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *AddClusterRequest) GetProviderDomain() string {
	if x != nil {
		return x.ProviderDomain
	}
	return ""
}

func (x *AddClusterRequest) GetSliceName() string {
	if x != nil {
		return x.SliceName
	}
	return ""
}

func (x *AddClusterRequest) GetCluster() *Cluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

type AddClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClusterResponse) Reset() {
	*x = AddClusterResponse{}
	mi := &file_l2sces_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClusterResponse) ProtoMessage() {}

func (x *AddClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClusterResponse.ProtoReflect.Descriptor instead.
func (*AddClusterResponse) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{20}
}

func (x *AddClusterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveClusterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderName   string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderDomain string                 `protobuf:"bytes,2,opt,name=provider_domain,json=providerDomain,proto3" json:"provider_domain,omitempty"`
	OverlayName    string                 `protobuf:"bytes,3,opt,name=overlay_name,json=overlayName,proto3" json:"overlay_name,omitempty"`
	ClusterName    string                 `protobuf:"bytes,4,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveClusterRequest) Reset() {
	*x = RemoveClusterRequest{}
	mi := &file_l2sces_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClusterRequest) ProtoMessage() {}

func (x *RemoveClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClusterRequest.ProtoReflect.Descriptor instead.
func (*RemoveClusterRequest) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveClusterRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *RemoveClusterRequest) GetProviderDomain() string {
	if x != nil {
		return x.ProviderDomain
	}
	return ""
}

func (x *RemoveClusterRequest) GetOverlayName() string {
	if x != nil {
		return x.OverlayName
	}
	return ""
}

func (x *RemoveClusterRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type RemoveClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveClusterResponse) Reset() {
	*x = RemoveClusterResponse{}
	mi := &file_l2sces_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClusterResponse) ProtoMessage() {}

func (x *RemoveClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClusterResponse.ProtoReflect.Descriptor instead.
func (*RemoveClusterResponse) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveClusterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteOverlayRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProviderName   string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderDomain string                 `protobuf:"bytes,2,opt,name=provider_domain,json=providerDomain,proto3" json:"provider_domain,omitempty"`
	OverlayName    string                 `protobuf:"bytes,3,opt,name=overlay_name,json=overlayName,proto3" json:"overlay_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteOverlayRequest) Reset() {
	*x = DeleteOverlayRequest{}
	mi := &file_l2sces_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOverlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOverlayRequest) ProtoMessage() {}

func (x *DeleteOverlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOverlayRequest.ProtoReflect.Descriptor instead.
func (*DeleteOverlayRequest) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteOverlayRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *DeleteOverlayRequest) GetProviderDomain() string {
	if x != nil {
		return x.ProviderDomain
	}
	return ""
}

func (x *DeleteOverlayRequest) GetOverlayName() string {
	if x != nil {
		return x.OverlayName
	}
	return ""
}

type DeleteOverlayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOverlayResponse) Reset() {
	*x = DeleteOverlayResponse{}
	mi := &file_l2sces_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOverlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOverlayResponse) ProtoMessage() {}

func (x *DeleteOverlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_l2sces_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOverlayResponse.ProtoReflect.Descriptor instead.
func (*DeleteOverlayResponse) Descriptor() ([]byte, []int) {
	return file_l2sces_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteOverlayResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_l2sces_proto protoreflect.FileDescriptor

const file_l2sces_proto_rawDesc = "" +
	"\n" +
	"\fl2sces.proto\x12\x06l2sces\"\xa9\x01\n" +
	"\bProvider\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x19\n" +
	"\bdns_port\x18\x03 \x01(\tR\adnsPort\x12\x19\n" +
	"\bsdn_port\x18\x04 \x01(\tR\asdnPort\x12\x17\n" +
	"\aof_port\x18\x05 \x01(\tR\x06ofPort\x12\"\n" +
	"\rdns_grpc_port\x18\x06 \x01(\tR\vdnsGrpcPort\"B\n" +
	"\x04Link\x12\x1c\n" +
	"\tendpointA\x18\x01 \x01(\tR\tendpointA\x12\x1c\n" +
	"\tendpointB\x18\x02 \x01(\tR\tendpointB\"9\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\"H\n" +
	"\n" +
	"RestConfig\x12!\n" +
	"\fbearer_token\x18\x01 \x01(\tR\vbearerToken\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\xf6\x01\n" +
	"\aCluster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\vrest_config\x18\x02 \x01(\v2\x12.l2sces.RestConfigR\n" +
	"restConfig\x12)\n" +
	"\aoverlay\x18\x03 \x01(\v2\x0f.l2sces.OverlayR\aoverlay\x12/\n" +
	"\fgateway_node\x18\x04 \x01(\v2\f.l2sces.NodeR\vgatewayNode\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12(\n" +
	"\x10pod_address_pool\x18\x06 \x01(\tR\x0epodAddressPool\"q\n" +
	"\aOverlay\x12,\n" +
	"\bprovider\x18\x01 \x01(\v2\x10.l2sces.ProviderR\bprovider\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\tR\x05nodes\x12\"\n" +
	"\x05links\x18\x03 \x03(\v2\f.l2sces.LinkR\x05links\"\xa9\x01\n" +
	"\tL2Network\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\bprovider\x18\x02 \x01(\v2\x10.l2sces.ProviderR\bprovider\x12\x19\n" +
	"\bpod_cidr\x18\x03 \x01(\tR\apodCidr\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12+\n" +
	"\bclusters\x18\x05 \x03(\v2\x0f.l2sces.ClusterR\bclusters\"\x86\x01\n" +
	"\x05Slice\x12,\n" +
	"\bprovider\x18\x01 \x01(\v2\x10.l2sces.ProviderR\bprovider\x12+\n" +
	"\bclusters\x18\x02 \x03(\v2\x0f.l2sces.ClusterR\bclusters\x12\"\n" +
	"\x05links\x18\x03 \x03(\v2\f.l2sces.LinkR\x05links\"a\n" +
	"\x14CreateNetworkRequest\x12+\n" +
	"\anetwork\x18\x01 \x01(\v2\x11.l2sces.L2NetworkR\anetwork\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"6\n" +
	"\n" +
	"FieldPatch\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"_\n" +
	"\x15CreateNetworkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12,\n" +
	"\apatches\x18\x02 \x03(\v2\x12.l2sces.FieldPatchR\apatches\"a\n" +
	"\x14DeleteNetworkRequest\x12+\n" +
	"\anetwork\x18\x01 \x01(\v2\x11.l2sces.L2NetworkR\anetwork\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"1\n" +
	"\x15DeleteNetworkResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\x12CreateSliceRequest\x12#\n" +
	"\x05slice\x18\x01 \x01(\v2\r.l2sces.SliceR\x05slice\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"/\n" +
	"\x13CreateSliceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"W\n" +
	"\x12DeleteSliceRequest\x12#\n" +
	"\x05slice\x18\x01 \x01(\v2\r.l2sces.SliceR\x05slice\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"/\n" +
	"\x13DeleteSliceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"A\n" +
	"\x14CreateOverlayRequest\x12)\n" +
	"\aoverlay\x18\x01 \x01(\v2\x0f.l2sces.OverlayR\aoverlay\"1\n" +
	"\x15CreateOverlayResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xab\x01\n" +
	"\x11AddClusterRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12'\n" +
	"\x0fprovider_domain\x18\x02 \x01(\tR\x0eproviderDomain\x12\x1d\n" +
	"\n" +
	"slice_name\x18\x03 \x01(\tR\tsliceName\x12)\n" +
	"\acluster\x18\x04 \x01(\v2\x0f.l2sces.ClusterR\acluster\".\n" +
	"\x12AddClusterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xaa\x01\n" +
	"\x14RemoveClusterRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12'\n" +
	"\x0fprovider_domain\x18\x02 \x01(\tR\x0eproviderDomain\x12!\n" +
	"\foverlay_name\x18\x03 \x01(\tR\voverlayName\x12!\n" +
	"\fcluster_name\x18\x04 \x01(\tR\vclusterName\"1\n" +
	"\x15RemoveClusterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x87\x01\n" +
	"\x14DeleteOverlayRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12'\n" +
	"\x0fprovider_domain\x18\x02 \x01(\tR\x0eproviderDomain\x12!\n" +
	"\foverlay_name\x18\x03 \x01(\tR\voverlayName\"1\n" +
	"\x15DeleteOverlayResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xf3\x04\n" +
	"\x16L2SMMultiDomainService\x12L\n" +
	"\rCreateNetwork\x12\x1c.l2sces.CreateNetworkRequest\x1a\x1d.l2sces.CreateNetworkResponse\x12L\n" +
	"\rDeleteNetwork\x12\x1c.l2sces.DeleteNetworkRequest\x1a\x1d.l2sces.DeleteNetworkResponse\x12F\n" +
	"\vCreateSlice\x12\x1a.l2sces.CreateSliceRequest\x1a\x1b.l2sces.CreateSliceResponse\x12F\n" +
	"\vDeleteSlice\x12\x1a.l2sces.DeleteSliceRequest\x1a\x1b.l2sces.DeleteSliceResponse\x12L\n" +
	"\rCreateOverlay\x12\x1c.l2sces.CreateOverlayRequest\x1a\x1d.l2sces.CreateOverlayResponse\x12C\n" +
	"\n" +
	"AddCluster\x12\x19.l2sces.AddClusterRequest\x1a\x1a.l2sces.AddClusterResponse\x12L\n" +
	"\rRemoveCluster\x12\x1c.l2sces.RemoveClusterRequest\x1a\x1d.l2sces.RemoveClusterResponse\x12L\n" +
	"\rDeleteOverlay\x12\x1c.l2sces.DeleteOverlayRequest\x1a\x1d.l2sces.DeleteOverlayResponseB3Z1github.com/Networks-it-uc3m/l2sc-es/api/v1/l2scesb\x06proto3"

var (
	file_l2sces_proto_rawDescOnce sync.Once
	file_l2sces_proto_rawDescData []byte
)

func file_l2sces_proto_rawDescGZIP() []byte {
	file_l2sces_proto_rawDescOnce.Do(func() {
		file_l2sces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_l2sces_proto_rawDesc), len(file_l2sces_proto_rawDesc)))
	})
	return file_l2sces_proto_rawDescData
}

var file_l2sces_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_l2sces_proto_goTypes = []any{
	(*Provider)(nil),              // 0: l2sces.Provider
	(*Link)(nil),                  // 1: l2sces.Link
	(*Node)(nil),                  // 2: l2sces.Node
	(*RestConfig)(nil),            // 3: l2sces.RestConfig
	(*Cluster)(nil),               // 4: l2sces.Cluster
	(*Overlay)(nil),               // 5: l2sces.Overlay
	(*L2Network)(nil),             // 6: l2sces.L2Network
	(*Slice)(nil),                 // 7: l2sces.Slice
	(*CreateNetworkRequest)(nil),  // 8: l2sces.CreateNetworkRequest
	(*FieldPatch)(nil),            // 9: l2sces.FieldPatch
	(*CreateNetworkResponse)(nil), // 10: l2sces.CreateNetworkResponse
	(*DeleteNetworkRequest)(nil),  // 11: l2sces.DeleteNetworkRequest
	(*DeleteNetworkResponse)(nil), // 12: l2sces.DeleteNetworkResponse
	(*CreateSliceRequest)(nil),    // 13: l2sces.CreateSliceRequest
	(*CreateSliceResponse)(nil),   // 14: l2sces.CreateSliceResponse
	(*DeleteSliceRequest)(nil),    // 15: l2sces.DeleteSliceRequest
	(*DeleteSliceResponse)(nil),   // 16: l2sces.DeleteSliceResponse
	(*CreateOverlayRequest)(nil),  // 17: l2sces.CreateOverlayRequest
	(*CreateOverlayResponse)(nil), // 18: l2sces.CreateOverlayResponse
	(*AddClusterRequest)(nil),     // 19: l2sces.AddClusterRequest
	(*AddClusterResponse)(nil),    // 20: l2sces.AddClusterResponse
	(*RemoveClusterRequest)(nil),  // 21: l2sces.RemoveClusterRequest
	(*RemoveClusterResponse)(nil), // 22: l2sces.RemoveClusterResponse
	(*DeleteOverlayRequest)(nil),  // 23: l2sces.DeleteOverlayRequest
	(*DeleteOverlayResponse)(nil), // 24: l2sces.DeleteOverlayResponse
}
var file_l2sces_proto_depIdxs = []int32{
	3,  // 0: l2sces.Cluster.rest_config:type_name -> l2sces.RestConfig
	5,  // 1: l2sces.Cluster.overlay:type_name -> l2sces.Overlay
	2,  // 2: l2sces.Cluster.gateway_node:type_name -> l2sces.Node
	0,  // 3: l2sces.Overlay.provider:type_name -> l2sces.Provider
	1,  // 4: l2sces.Overlay.links:type_name -> l2sces.Link
	0,  // 5: l2sces.L2Network.provider:type_name -> l2sces.Provider
	4,  // 6: l2sces.L2Network.clusters:type_name -> l2sces.Cluster
	0,  // 7: l2sces.Slice.provider:type_name -> l2sces.Provider
	4,  // 8: l2sces.Slice.clusters:type_name -> l2sces.Cluster
	1,  // 9: l2sces.Slice.links:type_name -> l2sces.Link
	6,  // 10: l2sces.CreateNetworkRequest.network:type_name -> l2sces.L2Network
	9,  // 11: l2sces.CreateNetworkResponse.patches:type_name -> l2sces.FieldPatch
	6,  // 12: l2sces.DeleteNetworkRequest.network:type_name -> l2sces.L2Network
	7,  // 13: l2sces.CreateSliceRequest.slice:type_name -> l2sces.Slice
	7,  // 14: l2sces.DeleteSliceRequest.slice:type_name -> l2sces.Slice
	5,  // 15: l2sces.CreateOverlayRequest.overlay:type_name -> l2sces.Overlay
	4,  // 16: l2sces.AddClusterRequest.cluster:type_name -> l2sces.Cluster
	8,  // 17: l2sces.L2SMMultiDomainService.CreateNetwork:input_type -> l2sces.CreateNetworkRequest
	11, // 18: l2sces.L2SMMultiDomainService.DeleteNetwork:input_type -> l2sces.DeleteNetworkRequest
	13, // 19: l2sces.L2SMMultiDomainService.CreateSlice:input_type -> l2sces.CreateSliceRequest
	15, // 20: l2sces.L2SMMultiDomainService.DeleteSlice:input_type -> l2sces.DeleteSliceRequest
	17, // 21: l2sces.L2SMMultiDomainService.CreateOverlay:input_type -> l2sces.CreateOverlayRequest
	19, // 22: l2sces.L2SMMultiDomainService.AddCluster:input_type -> l2sces.AddClusterRequest
	21, // 23: l2sces.L2SMMultiDomainService.RemoveCluster:input_type -> l2sces.RemoveClusterRequest
	23, // 24: l2sces.L2SMMultiDomainService.DeleteOverlay:input_type -> l2sces.DeleteOverlayRequest
	10, // 25: l2sces.L2SMMultiDomainService.CreateNetwork:output_type -> l2sces.CreateNetworkResponse
	12, // 26: l2sces.L2SMMultiDomainService.DeleteNetwork:output_type -> l2sces.DeleteNetworkResponse
	14, // 27: l2sces.L2SMMultiDomainService.CreateSlice:output_type -> l2sces.CreateSliceResponse
	16, // 28: l2sces.L2SMMultiDomainService.DeleteSlice:output_type -> l2sces.DeleteSliceResponse
	18, // 29: l2sces.L2SMMultiDomainService.CreateOverlay:output_type -> l2sces.CreateOverlayResponse
	20, // 30: l2sces.L2SMMultiDomainService.AddCluster:output_type -> l2sces.AddClusterResponse
	22, // 31: l2sces.L2SMMultiDomainService.RemoveCluster:output_type -> l2sces.RemoveClusterResponse
	24, // 32: l2sces.L2SMMultiDomainService.DeleteOverlay:output_type -> l2sces.DeleteOverlayResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_l2sces_proto_init() }
func file_l2sces_proto_init() {
	if File_l2sces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_l2sces_proto_rawDesc), len(file_l2sces_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_l2sces_proto_goTypes,
		DependencyIndexes: file_l2sces_proto_depIdxs,
		MessageInfos:      file_l2sces_proto_msgTypes,
	}.Build()
	File_l2sces_proto = out.File
	file_l2sces_proto_goTypes = nil
	file_l2sces_proto_depIdxs = nil
}
