kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: worker-cluster-1
networking:
    disableDefaultCNI: true  # Disable Kindnet, we will use Flannel as the primary CNI plugin
    podSubnet: "10.244.0.0/16"  # Flannel requires this CIDR
nodes:
- role: control-plane
  image: kindest/node:v1.26.6